CREATE TABLE VEGETABLES_FRUITS (
    ID SERIAL PRIMARY KEY,  
	PRODUCT_NAME VARCHAR(10) NOT NULL, 
    TYPE VARCHAR(10) NOT NULL, 
    COLOUR VARCHAR(10) NOT NULL,
    CALLORIES INT CHECK (CALLORIES > 0),
    DESCRIPTION VARCHAR(100) NOT NULL
);


INSERT INTO VEGETABLES_FRUITS(
	PRODUCT_NAME,
	TYPE,
	COLOUR,
	CALLORIES,
	DESCRIPTION 
)
VALUES
	('ANANAS', 'FRUIT', 'YELLOW', 300, 'SWEET, TASTY'),
    ('APPLE', 'FRUIT', 'RED', 52, 'CRISP, JUICY'),
    ('BANANA', 'FRUIT', 'YELLOW', 89, 'SOFT, SWEET'),
    ('CARROT', 'VEGETABLE', 'ORANGE', 41, 'CRUNCHY, SWEET'),
    ('SPINACH', 'VEGETABLE', 'GREEN', 23, 'LEAFY, NUTRITIOUS');