-- SELECT * FROM VEGETABLES_FRUITS
-- SELECT * FROM VEGETABLES_FRUITS WHERE TYPE = 'VEGETABLE'
-- SELECT PRODUCT_NAME FROM VEGETABLES_FRUITS WHERE TYPE = 'VEGETABLE'
-- SELECT PRODUCT_NAME FROM VEGETABLES_FRUITS WHERE TYPE = 'FRUIT'
-- SELECT DISTINCT COLOUR FROM VEGETABLES_FRUITS
-- SELECT PRODUCT_NAME FROM VEGETABLES_FRUITS WHERE TYPE = 'FRUIT' AND COLOUR = 'YELLOW'
-- SELECT PRODUCT_NAME FROM VEGETABLES_FRUITS WHERE TYPE = 'VEGETABLE' AND COLOUR = 'GREEN'



